name: kerchunk
channels:
  - conda-forge
  - default
dependencies:
  # - pangeo-notebook
  - jupyterlab
  # - jupyter-lab<3.3.0
  - pip
  - kerchunk
  - fsspec
  - s3fs
  - h5py
  - xarray[complete]
  - metpy
  - cartopy
  - cfgrib
  - eccodes
  - numpy
  - zstandard
  - hvplot
  - geoviews
  - intake
  - intake-xarray
  - datashader
  - nodejs
  - pip:
    - graphviz
    - jupyterlab-system-monitor
    - dask-labextension
